services:
  app-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app        # For code visibility during build
      - /app/node_modules      # Avoid overwriting node_modules
      - frontend-build:/app/build  # Share built files with Nginx
    environment:
      - NODE_ENV=production

  app-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/package.json:/app/package.json
      - ./Backend/tsconfig.json:/app/tsconfig.json
      - ./Backend/.env.dev:/app/.env.dev
      - ./Backend/uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"

  app-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ./nginx/ssl/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Backend/uploads:/app/uploads:ro
      - frontend-build:/usr/share/nginx/html:ro  # Serve React build files
    depends_on:
      - app-frontend
      - app-backend

volumes:
  frontend-build:   # Named volume for frontend build output
