
###
GET http://localhost:3000/health

### POST Request to Create User (valid request, should return user object)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "jhondoe",  
  "password":"123456",
  "email":"jhondoe@example.com"
}

### GET Request to Fetch All Users (valid request, should return all posts)
GET http://localhost:3000/users
Content-Type: application/json

### GET Request to get User by ID
GET http://localhost:3000/users/677026b7ad973b9da0e90ab1

### PUT Request to Update User by ID
PUT http://localhost:3000/users/677026b7ad973b9da0e90ab1
Content-Type: application/json

{
  "username": "janedoe",  
  "password":"1234567",
  "email":"janedoe@example.com"
}

### DELETE Request to Delete User by ID
DELETE http://localhost:3000/users/677026b7ad973b9da0e90ab1

### POST Request to Create Post (valid request, should return user object)
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Post 1",
  "content": "This is Post 1",  
  "userID":"677026cbad973b9da0e90ab9"
}

### GET Request to Fetch All Posts (valid request, should return all posts)
GET http://localhost:3000/posts
Content-Type: application/json

### GET Request to get Post by ID
GET http://localhost:3000/posts/677026822521efce0b2e0e15

### GET Request to Fetch All Posts by Sender ID (valid userID, should return posts for userID 123456)
GET http://localhost:3000/posts?userID=677026cbad973b9da0e90ab9
Content-Type: application/json

### PUT Request to Update Post by ID
PUT http://localhost:3000/posts/677026d4ad973b9da0e90abb
Content-Type: application/json

{
  "content": "This is Edited Post 1"
}

### DELETE Request to Delete Post by ID
DELETE http://localhost:3000/posts/677026a9ad973b9da0e90aaf

### Post a comment
POST http://localhost:3000/posts/677026d4ad973b9da0e90abb/comments
Content-Type: application/json

{
  "userID": "67701dd87deb50b9c16c0299",
  "content":"not goods"
}
### Get comments of post
GET  http://localhost:3000/posts/677026d4ad973b9da0e90abb/comments

###Get comment by id
GET  http://localhost:3000/posts/677026d4ad973b9da0e90abb/comments/677027caad973b9da0e90ad7

###Update comment of post
PUT  http://localhost:3000/posts/677026d4ad973b9da0e90abb/comments/677027caad973b9da0e90ad7
Content-Type: application/json

{
  "content":"Good"
}

###Delete comment of post
DELETE  http://localhost:3000/posts/677026d4ad973b9da0e90abb/comments/677027caad973b9da0e90ad7

#### Test Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "jhondoe",  
  "password":"123456",
  "email":"test@email.com"
}

#### Test Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@email.com", 
  "password":"123456"
}

### Test logout
POST  http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAxOTMwLCJleHAiOjE3MzYxMDU1MzB9.Rm7r5NgziIxm9Z9zGG7VZpAMR6MJNghwLGaUvy0X4zU eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAxOTMwLCJleHAiOjE3MzY3MDY3MzB9.ZeTzo_k5xOkSs-YZrX-BeiIOrJsIRQrgITj9amNCtPs

### Test refresh token 
POST  http://localhost:3000/auth/refresh
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAyNjY2LCJleHAiOjE3MzYxMDYyNjZ9.UMBN1QHn_m4AL1b4uwzmVIw-fOvRRha6qtviQm8bIVs eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAyNjY2LCJleHAiOjE3MzY3MDc0NjZ9.wUc9NcgH0ucQV-2RD-hSYuhTR3iZmC--RZqqsCb76rs
### Test Authentification
GET  http://localhost:3000/posts
Content-Type: application/json 
Authorization: eyJhbkciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAzNzgyLCJleHAiOjE3MzYxMDczODJ9.39aUflwUMRTQj3LFVBHkjKpYe1t3IL1NIkDiW8IAKjw eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3OTI5MjJlYmZmODNhM2FjMmQzNTA0IiwiaWF0IjoxNzM2MTAzNzgyLCJleHAiOjE3MzY3MDg1ODJ9.4Gx2F6O31H89VUoPZC6zd7nJhdoWqEqDtELYUFRw4QU