
###
GET http://localhost:3000/health

### POST Request to Create User (valid request, should return user object)
POST http://localhost:3000/posts
Content-Type: application/json

{
  "content": "This is Post 1",  
  "userID":"123456"
}

### GET Request to Fetch All Posts (valid request, should return all posts)
GET http://localhost:3000/posts
Content-Type: application/json

### GET Request to get Post by ID
GET http://localhost:3000/posts/676fc94c89d0609a0b797952

### GET Request to Fetch All Posts by Sender ID (valid userID, should return posts for userID 123456)
GET http://localhost:3000/posts?userID=123456
Content-Type: application/json

### PUT Request to Update Post by ID
PUT http://localhost:3000/posts/676fc94c89d0609a0b797952
Content-Type: application/json

{
  "content": "This is Edited Post 1"
}

### DELETE Request to Delete Post by ID
DELETE http://localhost:3000/posts/676fc94c89d0609a0b797952

### Post a comment
POST http://localhost:3000/posts/676fcbc7f2741262b07c225e/comments
Content-Type: application/json

{
  "userID": "123456",
  "content":"not goods"
}
### Get comments of post
GET  http://localhost:3000/posts/676fcbc7f2741262b07c225e/comments

###Get comment by id
GET  http://localhost:3000/posts/676fcbc7f2741262b07c225e/comments/676fcbd4f2741262b07c2260

###Update comment of post
PUT  http://localhost:3000/posts/676fc94c89d0609a0b797952/comments/676fc9a317b1839ad0188e0b
Content-Type: application/json

{
  "content":"Good"
}

###Delete comment of post
DELETE  http://localhost:3000/posts/676fc94c89d0609a0b797952/comments/676fc9a317b1839ad0188e0b


