
###
GET http://localhost:3000/health

###POST Request to Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "message": "Post 2",
  "sender": "123456"
}

### GET Request to Fetch All Posts (valid request, should return all posts)
GET http://localhost:3000/post
Content-Type: application/json

### GET Request to get Post by ID
GET http://localhost:3000/post/6735095ee481862a8af9de0d

### GET Request to Fetch All Posts by Sender ID (valid sender, should return posts for sender 123456)
GET http://localhost:3000/post?sender=123456
Content-Type: application/json

### PUT Request to Update Post by ID
PUT http://localhost:3000/post/6735095ee481862a8af9de0d
Content-Type: application/json

{
  "message": "Post 5",
  "sender": "176345"
}

### Post a comment
POST http://localhost:3000/post/6735134c982b40e6333ea2ac/comments
Content-Type: application/json

{
  "userID": "123456",
  "text":"not goods"
}
### get comments of post
GET  http://localhost:3000/post/6735095ee481862a8af9de0d/comments

###update comment of post
PUT  http://localhost:3000/post/6735095ee481862a8af9de0d/comments/67374f3b1979bca2a9b20a9b
Content-Type: application/json

{
  "text":"Good"
}



