### Health Check
GET http://localhost:3000/health

### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "jhondoe",  
  "password": "123456",
  "email": "test@email.com"
}

### Login to get tokens
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@email.com", 
  "password": "123456"
}

### Use the tokens obtained from the login response
### Replace <ACCESS_TOKEN> and <REFRESH_TOKEN> with the actual tokens

### Create User (requires authorization)
POST http://localhost:3000/users
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "username": "sampleuser",  
  "password": "123456",
  "email": "jhondoe@example.com"
}

### Fetch All Users
GET http://localhost:3000/users
Content-Type: application/json

### Get User by ID
GET http://localhost:3000/users/677be20d2a99b3e2b890650f

### Update User by ID (requires authorization)
PUT http://localhost:3000/users/677be20d2a99b3e2b890650f
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "username": "janedoe",  
  "password": "1234567",
  "email": "janedoe@example.com"
}

### Delete User by ID (requires authorization)
DELETE http://localhost:3000/users/677be1b22a99b3e2b89064ff
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ


### Create Post (requires authorization)
POST http://localhost:3000/posts
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "title": "Post 1",
  "content": "This is Post 1",  
  "userID": "677be20d2a99b3e2b890650f"
}

### Fetch All Posts
GET http://localhost:3000/posts
Content-Type: application/json

### Get Post by ID
GET http://localhost:3000/posts/677be5272a99b3e2b890653c

### Fetch All Posts by User ID
GET http://localhost:3000/posts?userID=677be20d2a99b3e2b890650f
Content-Type: application/json

### Update Post by ID (requires authorization)
PUT http://localhost:3000/posts/677be5272a99b3e2b890653c
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "content": "This is Edited Post 1"
}

### Delete Post by ID (requires authorization)
DELETE http://localhost:3000/posts/677be5272a99b3e2b890653c
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

### Post a comment (requires authorization)
POST http://localhost:3000/posts/677be5ad2a99b3e2b890654e/comments
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "userID": "677be20d2a99b3e2b890650f",
  "content": "Im Looking Great!"
}

### Get comments of post
GET http://localhost:3000/posts/677be5ad2a99b3e2b890654e/comments

### Get comment by ID
GET http://localhost:3000/posts/677be5ad2a99b3e2b890654e/comments/677be5e22a99b3e2b8906552

### Update comment of post (requires authorization)
PUT http://localhost:3000/posts/677be5ad2a99b3e2b890654e/comments/677be5e22a99b3e2b8906552
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

{
  "content": "Good"
}

### Delete comment of post (requires authorization)
DELETE http://localhost:3000/posts/677be5ad2a99b3e2b890654e/comments/677be5e22a99b3e2b8906552
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

### Logout (requires authorization)
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVkb2VAZXhhbXBsZS5jb20iLCJ1c2VySWQiOiI2NzdiZTIwZDJhOTliM2UyYjg5MDY1MGYiLCJyYW5kb20iOiIwLjMyMDk5MTc4Mzc0NjI3MzQ2IiwiaWF0IjoxNzM2MTczMTI0LCJleHAiOjE3MzYxNzY3MjR9.qxGqtaqfhIubJJbXEr4_nkvPij3U0CvMcoKThnau5qA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVkb2VAZXhhbXBsZS5jb20iLCJ1c2VySWQiOiI2NzdiZTIwZDJhOTliM2UyYjg5MDY1MGYiLCJyYW5kb20iOiIwLjg3MjExOTI1NjI5ODA4OCIsImlhdCI6MTczNjE3MzEyNCwiZXhwIjoxNzM2MTc2NzI0fQ.lt2RyyGZcAou4J1X6GpvDHREzrjCmNfj9WSw0VTZWNg 

### Refresh token (requires authorization)
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC40NTMxMDA0MTM5MjU1MzciLCJpYXQiOjE3MzYxNzIwNTUsImV4cCI6MTczNjE3NTY1NX0.NcJhcn48sRs0A4Od8G0v6qJO5ikFCvO1UBxcejFuhKA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjc3YmUyMGQyYTk5YjNlMmI4OTA2NTBmIiwicmFuZG9tIjoiMC4xMjI3NzM4MDEzMjEyODQ0NiIsImlhdCI6MTczNjE3MjA1NSwiZXhwIjoxNzM2MTc1NjU1fQ.OYdOPMiCaWONGr020BoLncuE2gpzM4H-47icAXgmEzQ

